# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b201b1240158cba137c3d4c2f6a4a65391d7451ff78a2fad5371512c84430e1793ab9abb9aad606f12a16f378cdb35a8ef7a05d10e8fffd2b299128a9d097f5

test:
  secret_key_base: 181eb08c0696c4dcebbf82c1d6a58f5cdc4150bd1a174b36cc4e7fec655b41fb865b9752eb96db472a222dbd713beb084c8a58097a35d2be7923f2152a0de488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
